[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_token_study = "26nVq6oP7XqZiaavfZCMhjDm1nGUrx4PRzoaKL2Vk3LY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/roster/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
